name: coverage

on:
  pull_request:
    paths:
      - '**.go'
      - '.github/workflows/coverage.yml'

env:
  go-version: '1.16'

jobs:
  coverage:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}
      - name: Install dependencies
        run: |
          GO111MODULE=off go get \
                 github.com/onsi/gomega \
                 github.com/onsi/ginkgo \
                 golang.org/x/tools/cmd/cover
      - run: go test -coverprofile=cover.out -covermode=count ./...
      - uses: codecov/codecov-action@v1
