---
name: test

"on":
  push:
    branches:
      - master
    paths:
      - 'go.mod'
      - 'go.sum'
      - '**.go'
      - '.github/workflows/test.yml'
  pull_request:
    paths:
      - 'go.mod'
      - 'go.sum'
      - '**.go'
      - '.github/workflows/test.yml'

env:
  go-version: '1.16'

jobs:
  test:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      matrix:
        include:
          - os: windows
            runs-on: windows-latest
            opts: -cover -tags windows
          - os: linux
            runs-on: ubuntu-latest
            opts: -cover
          - os: darwin
            runs-on: macOS-latest
            opts: -cover
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go-version }}
      - run: go build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: amd64
      - run: go test ${{ matrix.opts }} ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.go-version }}
      - uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: v1.45
          args: --issues-exit-code=0
          only-new-issues: true
